import type { Metadata } from "next";
import localFont from "next/font/local";

import Example from "./fonts/Example";
import "./globals.css";

[].forEach((item) => {
  console.log(item);
});

const firstName = "Akshay";
const lastName = "Rk";

const fullName = `${firstName} ${lastName}`;
console.log(fullName);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Example />
        {children}
      </body>
    </html>
  );
}
